### ISSUE TITLE
Unable to retrieve result even after changing API Key

### ISSUE THREAD

**Issue by mehtanilay10** [Azure-Samples/cognitive-services-dotnet-sdk-samples#25]
> Unable to retrieve result from API
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report 
- [ x ] documentation issue or request
```

### Minimal steps to reproduce
> Change key and run it.

##### One or more errors occurred. (Operation returned an invalid status code 'Unauthorized')
> at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ComputerVisionSample.Program.Main(String[] args) in C:\Users\mehta\Downloads\cognitive-services-dotnet-sdk-samples-master\cognitive-services-dotnet-sdk-samples-master\ComputerVision\Program.cs:line 24

### Expected/desired behavior
> Should connect to API

### OS and Version?
> Windows 10.

### Versions
> 1.0.1-Preview

**Comment by mehtanilay10** [comment]
Got solution!
I was changed Key but forget to change AzureRegion.
