### ISSUE TITLE
CustomVision/ObjectDetection throws

### ISSUE THREAD

**Issue by easyj2j** [Azure-Samples/cognitive-services-dotnet-sdk-samples#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

`var project = trainingApi.CreateProject("My New Project", null, objDetectionDomain.Id);`

throws: 'Forbidden'

Replace `objDetectionDomain.Id` with null and project creation is successful but the returned BoundingBox's are null. Prediction is valid.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by isinghrana** [comment]
I have exactly the same issue where I am unable to create the project for ObjectDetection Domain. Following is the detailed exception message



Microsoft.Rest.HttpOperationException
  HResult=0x80131500
  Message=Operation returned an invalid status code 'Forbidden'
  Source=Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training
  StackTrace:
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApi.<CreateProjectWithHttpMessagesAsync>d__45.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.<CreateProjectAsync>d__70.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.CreateProject(ITrainingApi operations, String name, String description, Nullable`1 domainId, String classificationType)
   at ObjectDetection.Program.Main(String[] args) in C:\mylearning\laibc-lab01.3-cv02\CustomVision.Sample\ObjectDetection\Program.cs:line 36

**Comment by easyj2j** [comment]
Good catch! and verified.

This needs to be doc'ed.

Also verified that samples work with upgrade to Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training 0.12.0-preview

**Comment by easyj2j** [comment]
```
// If not using 'Limited trial' keys -> HttpOperationException: Forbidden
// When using 'Limited trial' and # of projects = 2 (max) -> HttpOperationException: Bad Request
var project = trainingApi.CreateProject("My New Project", null, objDetectionDomain.Id);
```
